### ISSUE TITLE
Getting Error On Vue3

### ISSUE THREAD

**Issue by ariealdiansyah** [pratik227/echarts-quasar#1]
getting error like this
wrapper.js?c7c1:417 Uncaught (in promise) TypeError: h is not a function
at Proxy.render (wrapper.js?c7c1:417:1)
at renderComponentRoot (runtime-core.esm-bundler.js?9e79:893:1)

**Comment by pratik227** [comment]
You are using Vue 3?

For vue 3 use this NPM - https://www.npmjs.com/package/vue3-echarts-v3

**Comment by pratik227** [comment]
Closing this issue
